name: mayo_components
description: This package contains common components like fields, text areas, etc. Shared between different applications
version: 0.0.1
homepage: https://mayosoftware.es

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dotted_decoration: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dropzone: ^3.0.5
  fluttertoast: ^8.1.1
  formz: ^0.6.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0