name: mayo_components
description: This package contains common components like fields, text areas, etc. Shared between different applications
version: 0.0.26
homepage: https://mayosoftware.es

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^6.0.0
  cached_network_image: ^3.2.3
  
  # data_exporter:
  #   path: ./data_exporter

  dotted_decoration: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.0.1
  formz: ^0.8.0
  responsive_framework: ^1.5.1

  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0