name: mayo_components
description: This package contains common components like fields, text areas, etc. Shared between different applications
version: 0.0.1
homepage: https://mayosoftware.es

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  formz: ^0.4.0
  very_good_analysis: ^3.0.1