name: data_exporter
description: "This package provides a data exporter for Flutter applications. It allows exporting data in various formats such as CSV, JSON, and XML. The package is designed to be easy to use and integrate into existing Flutter projects."
version: 0.0.2
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^6.0.0
  share_plus: ^11.0.0
  path_provider: ^2.1.3
  pdf: ^3.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
